# Generated by Django 4.0.4 on 2022-05-21 09:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("post_barcode", models.IntegerField(default=0, unique=True)),
                ("post_title", models.CharField(max_length=250)),
                (
                    "post_short_description",
                    models.CharField(
                        default="Краткое описание",
                        max_length=250,
                        verbose_name="Краткое описание",
                    ),
                ),
                ("post_text", models.TextField(verbose_name="Полное описание")),
                ("post_created", models.DateTimeField(auto_now_add=True)),
                ("post_updated", models.DateTimeField(auto_now=True)),
                ("post_slug", models.SlugField()),
                ("post_rating", models.IntegerField(default=0)),
                ("post_count_view", models.IntegerField(default=0)),
                (
                    "post_author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "post_user_dislike",
                    models.ManyToManyField(
                        blank=True,
                        default=None,
                        related_name="post_disliked",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "post_user_favorite",
                    models.ManyToManyField(
                        blank=True,
                        default=None,
                        related_name="favorite",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "post_user_like",
                    models.ManyToManyField(
                        blank=True,
                        default=None,
                        related_name="post_liked",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-post_created"],
            },
            managers=[
                ("post_objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name="Images",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.FileField(blank=True, null=True, upload_to="static/img/"),
                ),
                (
                    "post",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="blog.post",
                    ),
                ),
            ],
        ),
    ]
